### ISSUE TITLE
subprocess.CalledProcessError: Command '['java', '-cp', './external/datagen.jar:./external/lib/*', '-ea', 'datagen.Main', 'equiv', 'endwith(or(<vow>,<cap>))', 'endwith(or(<cap>,<vow>))']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by AviVarma** [xiye17/torchASN#1]
When running  ./scripts/turk/test.sh checkpoints/turk/pretrained.bin The following error is outputted:

Decoding: 100%|##########| 2500/2500 [06:07<00:00,  6.79it/s]
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    test(args)
  File "test.py", line 72, in test
    eq_res = check_equiv(pred_code, gt_code)
  File "test.py", line 30, in check_equiv
    out = subprocess.check_output(
  File "C:\Users\AviVarma\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\AviVarma\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-cp', './external/datagen.jar:./external/lib/*', '-ea', 'datagen.Main', 'equiv', 'endwith(or(<vow>,<cap>))', 'endwith(or(<cap>,<vow>))']' returned non-zero exit status 1.

**Comment by xiye17** [comment]
can you directly run the command on your cmd and check the output.
It seems to be some issues when invoking java ( sth with the java environment or dependencies)

**Comment by AviVarma** [comment]
So After running the following directly into the CMD: python -u test.py --test_file data/turk/test.bin --model_file checkpoints/turk/pretrained.bin --beam_size 10 --max_decode_step 70 
I get the same error:
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    test(args)
  File "test.py", line 72, in test
    eq_res = check_equiv(pred_code, gt_code)
  File "test.py", line 30, in check_equiv
    out = subprocess.check_output(
  File "C:\Users\AviVarma\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\AviVarma\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-cp', './external/datagen.jar:./external/lib/*', '-ea', 'datagen.Main', 'equiv', 'endwith(or(<vow>,<cap>))', 'endwith(or(<cap>,<vow>))']' returned non-zero exit status 1.

**Comment by xiye17** [comment]
I mean run this command invoked  by subprocess
'['java', '-cp', './external/datagen.jar:./external/lib/', '-ea', 'datagen.Main', 'equiv', 'endwith(or(,))', 'endwith(or(,))']' 
java -cp ./external/datagen.jar:./external/lib/ -ea datagen.Main equiv endwith(or(,)) endwith(or(,))

**Comment by AviVarma** [comment]
input:
java -cp ./external/datagen.jar:./external/lib/ -ea datagen.Main equiv endwith(or(,)) endwith(or(,))

output:
At line:1 char:84
+ ... tagen.jar:./external/lib/ -ea datagen.Main equiv endwith(or(,)) endwi ...
+                                                                  ~
Missing expression after unary operator ','.
At line:1 char:99
+ ... :./external/lib/ -ea datagen.Main equiv endwith(or(,)) endwith(or(,))
+                                                                        ~
Missing expression after unary operator ','.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

**Comment by AviVarma** [comment]
input:
`java -cp ./external/datagen.jar:./external/lib/ -ea datagen.Main equiv endwith(or(,)) endwith(or(,))`
output:
```
At line:1 char:84
+ ... tagen.jar:./external/lib/ -ea datagen.Main equiv endwith(or(,)) endwi ...
+                                                                  ~
Missing expression after unary operator ','.
At line:1 char:99
+ ... :./external/lib/ -ea datagen.Main equiv endwith(or(,)) endwith(or(,))
+                                                                        ~
Missing expression after unary operator ','.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator
```

**Comment by xiye17** [comment]
can you paste the output of this (added some quotations)
java -cp "./external/datagen.jar:./external/lib/*" -ea datagen.Main equiv "endwith(or(,))" "endwith(or(,))"

**Comment by AviVarma** [comment]
input:

```
java -cp "./external/datagen.jar:./external/lib/*" -ea datagen.Main equiv "endwith(or(,))" "endwith(or(,))"
```

output:
```
Error: Could not find or load main class datagen.Main
Caused by: java.lang.ClassNotFoundException: datagen.Main
```

**Comment by xiye17** [comment]
Yes it's java related problem.  ​Basically, the main class wasn't loaded. 
This command works on my macOS and ubuntu. Maybe it's Windows related issue. I assume you are using CMD or powershell.
Can you run the code on bash or linux-based OS? Or you may want to slightly modify the command and then `test.py` line 31-32 accordingly to fit windows. (I don't have windows so I am not sure how to do it.

**Comment by AviVarma** [comment]
Yes I'm trying this on windows cmd. I have a spare linux machine, I'll get this setup and see it works my end. and try to find a solution for windows. :)

**Comment by AviVarma** [comment]
Right I found the solution!

On windows you need to replace the `:` with `;` So the input for windows cmd/ powershell:

```
java -cp "./external/datagen.jar;./external/lib/*" -ea datagen.Main equiv "endwith(or(,))" "endwith(or(,))"
```

To resolve this issue when runing the command `./scripts/turk/test.sh <model_file>` do the following for **Windows**:

+ Go to line `33 - 35` in `test.py` which should look like:
```
out = subprocess.check_output(
        ['java', '-cp', './external/datagen.jar:./external/lib/*', '-ea', 'datagen.Main', 'equiv',
            spec0, spec1], stderr=subprocess.DEVNULL)
```
+ Replace this with:
```
out = subprocess.check_output(
        ['java', '-cp', './external/datagen.jar;./external/lib/*', '-ea', 'datagen.Main', 'equiv',
            spec0, spec1], stderr=subprocess.DEVNULL)
```
